"""add auth

Revision ID: 56d3f9434a17
Revises: 023bdbbfba06
Create Date: 2024-03-28 09:03:21.376769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56d3f9434a17'
down_revision = '023bdbbfba06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.alter_column('date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    op.drop_table('post')
    # ### end Alembic commands ###
